version: build-{build}

clone_depth: 1

skip_tags: true

os: Visual Studio 2015

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"
  MSVCVERSION: "v140"
  MSVCYEAR: "vs2015"
  matrix:
    - platform: Win32
      configuration: Release
    - platform: Win32
      configuration: Debug
    - platform: x64
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: Win32
      configuration: Release
    - platform: Win32
      configuration: Release
    - platform: Win32
      configuration: Release

matrix:
  fast_finish: false

init:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmake --version
  - msbuild /version
  - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f

install:
  - cmd: if "%Platform%"=="x64" set "CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64"
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"

before_build:
  - cmd: set CPPSQL_BUILDDIR=C:\projects\test
  - cd "%LIBZMQ_BUILDDIR%"
  - cmd: cmake -G "%CMAKE_GENERATOR%" "%APPVEYOR_BUILD_FOLDER%"

build:
  parallel: true
  project: C:\projects\test\CppSQL.sln
  verbosity: minimal
